services:
  - name: api-auth
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
<<<<<<< HEAD
        value: 10000
=======
        value: 10000
>>>>>>> 03463f1c931d051f3baa6bcd81f4e6ebd78576a3
